version: '2'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
  web:
    build: .
    command: ./bin/start
    ports:
      - "3000:3000"
    environment:
      RACK_ENV: development
      RAILS_ENV: development
    depends_on:
      - db
      - box
    volumes_from:
      - box
    volumes:
      - .:/waypoint
  box:
    image: busybox
    volumes:
      - /box
